framework:
    messenger:
        transports:
            kafka_consumer:
                dsn: 'kafka://%env(KAFKA_BROKERS)%?topics=cart-events&group=promotion-consumer'

        routing:
            'Nocart\SharedKernel\Infrastructure\Messenger\Message\ExternalEventMessage': kafka_consumer
